import type { Icon } from '@/types';
import coordinatesJson from './coordinates.json';

/** Geographic coordinate of a city (WGS84 degrees). */
export interface CityCoordinate {
  lat: number;
  lng: number;
}

// coordinates.json is generated by scripts/build-city-coordinates.mjs and maps
// icon _id -> [lat, lng]. JSON imports widen tuples to number[], so read
// defensively here instead of casting.
const coords: Record<string, number[]> = coordinatesJson.coords;

/** Coordinate for an icon, or null if the dataset has no entry for it yet. */
export function getCoordinate(icon: Icon): CityCoordinate | null {
  const pair = coords[icon._id];
  if (!pair || pair.length !== 2) return null;
  return { lat: pair[0], lng: pair[1] };
}

/**
 * Icons missing from the coordinates dataset — non-empty means
 * `node scripts/build-city-coordinates.mjs` needs a re-run after new icons
 * were added. Callers should surface this loudly at build time.
 */
export function getIconsMissingCoordinates(icons: Icon[]): Icon[] {
  return icons.filter((icon) => getCoordinate(icon) === null);
}
